/api/users/
/api/tags/
/api/tags/{id}/
/api/recipes/
/api/recipes/download_shopping_cart/
/api/recipes/{id}/
/api/recipes/{id}/get-link/
/api/recipes/{id}/favorite/
/api/recipes/{id}/shopping_cart/
/api/users/{id}/
/api/users/me/
/api/users/me/avatar/
/api/users/subscriptions/
/api/users/{id}/subscribe/
/api/ingredients/
/api/ingredients/{id}/
/api/users/set_password/
/api/auth/token/login/